import { Platform, StyleSheet } from 'react-native';

const palette = {
  background: '#F7F7F5',
  surface: '#FFFFFF',
  text: '#252523',
  muted: '#74746E',
  border: '#E1E1DD',
  userBubble: '#ECECEA',
  warm: '#F0E9DF',
  warmDark: '#765D45',
  dark: '#292927',
  green: '#4F6B5B',
  red: '#A8463B',
};

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: palette.background },
  fill: { flex: 1 },
  safeTop: { height: Platform.OS === 'ios' ? 52 : 28, backgroundColor: palette.background },
  centeredPage: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.background },
  loadingMark: { marginTop: 20 },

  setupPage: { flex: 1, backgroundColor: palette.background },
  setupContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: Platform.OS === 'ios' ? 86 : 56, paddingBottom: 40 },
  setupEyebrow: { marginTop: 26, color: palette.warmDark, fontSize: 11, letterSpacing: 1.8, fontWeight: '700' },
  setupTitle: { marginTop: 8, color: palette.text, fontSize: 42, lineHeight: 48, fontWeight: '600' },
  setupCopy: { marginTop: 12, marginBottom: 28, color: palette.muted, fontSize: 17, lineHeight: 25 },

  chatControls: {
    position: 'absolute',
    top: 4,
    right: 10,
    zIndex: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  headerButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#DEDED9',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.94)',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  memoryBadge: {
    position: 'absolute',
    right: 0,
    top: 1,
    minWidth: 16,
    height: 16,
    borderRadius: 8,
    paddingHorizontal: 4,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.warmDark,
  },
  memoryBadgeText: { color: '#FFFFFF', fontSize: 9, fontWeight: '800' },

  chatListContent: { paddingHorizontal: 16, paddingTop: 58, paddingBottom: 16 },
  chatListEmpty: { flexGrow: 1, justifyContent: 'flex-start', paddingTop: 28 },
  chatListFooter: { height: 12 },
  emptyConversation: { alignItems: 'center', paddingHorizontal: 8, paddingBottom: 18 },
  emptyConversationTitle: { marginTop: 22, color: palette.text, fontSize: 25, lineHeight: 31, fontWeight: '600', textAlign: 'center' },
  emptyConversationCopy: { maxWidth: 320, marginTop: 10, color: palette.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  promptList: { alignSelf: 'stretch', marginTop: 28, gap: 10 },
  promptChip: {
    minHeight: 54,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: palette.border,
    borderRadius: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: palette.surface,
  },
  promptChipText: { flex: 1, color: '#454541', fontSize: 14.5, lineHeight: 20 },
  promptArrow: { marginLeft: 12, color: palette.muted, fontSize: 18 },

  userMessageRow: { alignItems: 'flex-end', marginBottom: 22, paddingLeft: 48 },
  userBubble: {
    maxWidth: '92%',
    overflow: 'hidden',
    borderRadius: 22,
    borderBottomRightRadius: 7,
    backgroundColor: palette.userBubble,
  },
  userPhoto: { width: 248, maxWidth: '100%', height: 210, backgroundColor: '#D8D8D4' },
  userBubbleText: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 13, color: palette.text, fontSize: 16, lineHeight: 23 },
  userTagRow: { marginTop: -5, paddingHorizontal: 14, paddingBottom: 11, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  userTag: { color: palette.warmDark, fontSize: 11.5, fontWeight: '700' },
  userBubbleMeta: { marginTop: -7, paddingHorizontal: 16, paddingBottom: 12, color: palette.muted, fontSize: 11.5 },
  assistantRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 24, paddingRight: 28 },
  assistantContent: { flex: 1, paddingTop: 3 },
  assistantText: { color: palette.text, fontSize: 16, lineHeight: 24 },
  assistantError: { color: palette.red },
  typingPill: {
    height: 34,
    paddingHorizontal: 13,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    backgroundColor: palette.warm,
  },
  typingDot: { width: 5, height: 5, borderRadius: 3, backgroundColor: '#8A7764' },

  composerArea: {
    paddingHorizontal: 12,
    paddingTop: 7,
    paddingBottom: Platform.OS === 'ios' ? 14 : 10,
    backgroundColor: palette.background,
  },
  attachmentPreview: {
    marginBottom: 8,
    minHeight: 78,
    padding: 8,
    borderWidth: 1,
    borderColor: '#DDD7CE',
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FAF7F2',
  },
  attachmentImage: { width: 50, height: 50, borderRadius: 12, backgroundColor: '#DDD8D0' },
  attachmentCopy: { flex: 1, marginHorizontal: 11 },
  attachmentTitle: { color: palette.text, fontSize: 14, fontWeight: '700' },
  attachmentMeta: { marginTop: 3, color: palette.muted, fontSize: 11.5 },
  attachmentHistory: { marginTop: 3, color: '#969087', fontSize: 10.5 },
  removeAttachment: { width: 32, height: 32, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#ECE7DF' },
  removeAttachmentText: { color: palette.text, fontSize: 22, lineHeight: 24 },
  selectedTagRow: { paddingHorizontal: 3, paddingBottom: 7, gap: 6 },
  selectedTagChip: {
    height: 30,
    paddingLeft: 11,
    paddingRight: 8,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.warm,
  },
  selectedTagText: { color: palette.warmDark, fontSize: 12.5, fontWeight: '700' },
  tagSuggestions: {
    marginBottom: 7,
    minHeight: 30,
    justifyContent: 'center',
  },
  tagSuggestionRow: { paddingHorizontal: 3, gap: 6 },
  tagSuggestionChip: {
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 15,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: '#D8D4CD',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.surface,
  },
  tagSuggestionText: { color: '#555550', fontSize: 12.5, fontWeight: '600' },
  createTagChip: { flexDirection: 'row', gap: 2, borderColor: '#C9D6CE', backgroundColor: '#EEF4F0' },
  createTagText: { color: palette.green, fontSize: 12.5, fontWeight: '700' },
  tagSuggestionHint: { paddingHorizontal: 7, color: palette.muted, fontSize: 12 },
  composer: {
    minHeight: 52,
    maxHeight: 126,
    paddingHorizontal: 6,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: '#D1D1CC',
    borderRadius: 27,
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: palette.surface,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.07,
    shadowRadius: 8,
    elevation: 3,
  },
  composerTools: { flexDirection: 'row', alignItems: 'center', gap: 1, marginLeft: 2, marginRight: 2 },
  composerToolButton: { width: 36, height: 40, borderRadius: 18, alignItems: 'center', justifyContent: 'center' },
  composerInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 110,
    paddingHorizontal: 7,
    paddingTop: 9,
    paddingBottom: 8,
    color: palette.text,
    fontSize: 16,
    lineHeight: 22,
    textAlignVertical: 'center',
  },
  sendButton: { width: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.dark },
  sendButtonDisabled: { backgroundColor: '#D3D3CF' },

  pageHeader: {
    height: 62,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: palette.border,
    backgroundColor: palette.surface,
  },
  backButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center' },
  backButtonText: { color: palette.text, fontSize: 35, lineHeight: 37, fontWeight: '300' },
  pageHeaderCopy: { flex: 1, alignItems: 'center' },
  pageHeaderTitle: { color: palette.text, fontSize: 17, fontWeight: '700' },
  pageHeaderSubtitle: { marginTop: 2, color: palette.muted, fontSize: 11.5 },
  pageHeaderSpacer: { width: 42 },

  memoryList: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 32, gap: 16 },
  memoryListEmpty: { flexGrow: 1, justifyContent: 'center' },
  galleryEmpty: { alignItems: 'center', paddingHorizontal: 36 },
  galleryEmptyTitle: { marginTop: 18, color: palette.text, fontSize: 22, fontWeight: '600' },
  galleryEmptyCopy: { marginTop: 8, color: palette.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  memoryCard: { overflow: 'hidden', borderWidth: 1, borderColor: palette.border, borderRadius: 22, backgroundColor: palette.surface },
  inlineMemoryCard: { marginTop: 15, borderRadius: 18 },
  memoryImage: { width: '100%', aspectRatio: 1.45, backgroundColor: '#DDD8D0' },
  inlineMemoryImage: { aspectRatio: 1.7 },
  memoryBody: { padding: 15 },
  memoryMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  memoryDate: { color: palette.muted, fontSize: 11.5, fontWeight: '600' },
  pill: {
    overflow: 'hidden',
    borderRadius: 11,
    paddingHorizontal: 9,
    paddingVertical: 3,
    color: palette.green,
    backgroundColor: '#E7EFEA',
    fontSize: 11,
    fontWeight: '700',
  },
  memoryDescription: { marginTop: 9, color: palette.text, fontSize: 17, lineHeight: 23, fontWeight: '500' },
  inlineMemoryDescription: { fontSize: 15.5, lineHeight: 21 },
  memoryTags: { marginTop: 9, flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  memoryTag: {
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 4,
    borderRadius: 11,
    color: palette.warmDark,
    backgroundColor: palette.warm,
    fontSize: 11.5,
    fontWeight: '700',
  },
  memoryPlace: { marginTop: 8, color: palette.muted, fontSize: 12.5 },
  memoryHistory: { marginTop: 10, color: '#8A8A84', fontSize: 10.5, lineHeight: 15 },
  mapLink: { marginTop: 9, color: '#6D5239', fontSize: 12.5, fontWeight: '700' },

  settingsContent: { paddingTop: 20, paddingBottom: 40 },
  connectionCard: { marginHorizontal: 16, padding: 18, borderWidth: 1, borderColor: palette.border, borderRadius: 22, backgroundColor: palette.surface },
  field: { marginBottom: 17 },
  fieldLabel: { marginBottom: 7, color: '#555550', fontSize: 12, fontWeight: '700' },
  input: {
    minHeight: 49,
    borderWidth: 1,
    borderColor: '#D4D4CF',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: palette.text,
    backgroundColor: palette.background,
    fontSize: 15.5,
  },
  errorText: { marginBottom: 14, color: palette.red, fontSize: 13, lineHeight: 18 },
  primaryButton: { minHeight: 50, borderRadius: 15, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.dark },
  primaryButtonText: { color: '#FFFFFF', fontSize: 15.5, fontWeight: '700' },
  disabledButton: { opacity: 0.5 },
  noteCard: { marginHorizontal: 16, marginTop: 14, padding: 18, borderWidth: 1, borderColor: palette.border, borderRadius: 18, backgroundColor: palette.surface },
  noteCardTitle: { marginBottom: 7, color: palette.text, fontSize: 15, fontWeight: '700' },
  noteCardText: { color: palette.muted, fontSize: 13.5, lineHeight: 20 },
});

