import { Platform, StyleSheet } from 'react-native';

const serif = Platform.OS === 'ios' ? 'Georgia' : 'serif';

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: '#F5F0E8' },
  fill: { flex: 1 },
  page: { flex: 1 },
  safeTop: { height: Platform.OS === 'ios' ? 52 : 28, backgroundColor: '#F5F0E8' },
  centeredPage: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#F5F0E8' },
  setupPage: { flex: 1, backgroundColor: '#F5F0E8' },
  setupContent: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 76, paddingBottom: 40 },
  brandMarkImage: { width: 64, height: 64, borderRadius: 20 },
  setupEyebrow: { marginTop: 28, color: '#8B6D4F', fontSize: 11, letterSpacing: 2.2, fontWeight: '700' },
  setupTitle: { marginTop: 8, color: '#252822', fontSize: 44, lineHeight: 50, fontWeight: '600', fontFamily: serif },
  setupCopy: { marginTop: 12, marginBottom: 26, color: '#665F56', fontSize: 17, lineHeight: 26 },
  header: { paddingHorizontal: 20, paddingTop: 18, paddingBottom: 18 },
  eyebrow: { color: '#8B6D4F', fontSize: 11, letterSpacing: 2.1, fontWeight: '700' },
  title: { marginTop: 5, color: '#252822', fontSize: 34, lineHeight: 41, fontWeight: '600', fontFamily: serif },
  subtitle: { marginTop: 6, color: '#766E64', fontSize: 15, lineHeight: 21 },
  scrollContent: { paddingBottom: 40 },
  listContent: { paddingBottom: 32 },
  emptyListContent: { flexGrow: 1, paddingBottom: 32 },
  emptyCard: { marginHorizontal: 20, marginTop: 32, padding: 26, borderRadius: 26, backgroundColor: '#E7DDCE', alignItems: 'flex-start' },
  emptyGlyph: { color: '#8B6D4F', fontSize: 29 },
  emptyTitle: { marginTop: 12, color: '#252822', fontSize: 24, fontWeight: '600', fontFamily: serif },
  emptyCopy: { marginTop: 8, marginBottom: 20, color: '#665F56', fontSize: 15, lineHeight: 22 },
  memoryCard: {
    marginHorizontal: 20, marginBottom: 18, borderRadius: 24, overflow: 'hidden', backgroundColor: '#FFFDFC',
    shadowColor: '#6A5A46', shadowOpacity: 0.09, shadowRadius: 18, shadowOffset: { width: 0, height: 8 }, elevation: 3,
  },
  memoryImage: { width: '100%', aspectRatio: 1.35, backgroundColor: '#DDD4C8' },
  memoryBody: { padding: 18 },
  memoryMetaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  memoryDate: { color: '#8A8177', fontSize: 12, fontWeight: '600' },
  pill: { overflow: 'hidden', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, color: '#53645B', backgroundColor: '#E4ECE6', fontSize: 12, fontWeight: '600' },
  memoryDescription: { marginTop: 10, color: '#292B27', fontSize: 18, lineHeight: 25, fontFamily: serif },
  memoryTags: { marginTop: 10, color: '#806A52', fontSize: 13 },
  memoryPlace: { marginTop: 9, color: '#6D746E', fontSize: 13 },
  mapLink: { marginTop: 10, color: '#8B5E38', fontSize: 13, fontWeight: '700' },
  score: { marginTop: 10, color: '#8A8177', fontSize: 11, letterSpacing: 0.4 },
  photoChooser: { marginHorizontal: 20, marginBottom: 22, borderWidth: 1.5, borderStyle: 'dashed', borderColor: '#B5A48F', borderRadius: 24, padding: 28, alignItems: 'center', backgroundColor: '#EFE7DC' },
  photoGlyph: { color: '#856A4E', fontSize: 38 },
  photoTitle: { marginTop: 10, marginBottom: 18, color: '#383B35', fontSize: 18, fontWeight: '600' },
  photoPreview: { marginHorizontal: 20, height: 250, borderRadius: 24, backgroundColor: '#DDD4C8' },
  changePhoto: { marginTop: 9, marginBottom: 20, color: '#806A52', textAlign: 'center', fontSize: 13 },
  buttonRow: { flexDirection: 'row', gap: 10 },
  field: { marginHorizontal: 20, marginBottom: 18 },
  fieldLabel: { marginBottom: 7, color: '#5B574F', fontSize: 12, fontWeight: '700', letterSpacing: 0.35 },
  input: { minHeight: 48, borderWidth: 1, borderColor: '#D6CCBF', borderRadius: 14, paddingHorizontal: 14, paddingVertical: 12, color: '#252822', backgroundColor: '#FFFDFC', fontSize: 16 },
  multilineInput: { minHeight: 100, textAlignVertical: 'top' },
  twoColumns: { flexDirection: 'row', marginHorizontal: 10 },
  column: { flex: 1 },
  locationButton: { marginHorizontal: 20, marginBottom: 18, borderRadius: 14, padding: 15, backgroundColor: '#E1E8E2' },
  locationButtonText: { color: '#47574E', fontSize: 14, fontWeight: '700', textAlign: 'center' },
  primaryButton: { minHeight: 52, marginHorizontal: 20, borderRadius: 16, paddingHorizontal: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: '#2F3A34' },
  primaryButtonText: { color: '#FFF8EA', fontSize: 16, fontWeight: '700' },
  disabledButton: { opacity: 0.55 },
  secondaryButton: { borderWidth: 1, borderColor: '#B7A58E', borderRadius: 13, paddingHorizontal: 14, paddingVertical: 11, backgroundColor: '#F8F3EC' },
  secondaryButtonText: { color: '#66513D', fontSize: 13, fontWeight: '700' },
  searchRow: { flexDirection: 'row', marginHorizontal: 20, marginBottom: 22, gap: 10 },
  searchInput: { flex: 1, height: 52, borderWidth: 1, borderColor: '#D6CCBF', borderRadius: 16, paddingHorizontal: 16, color: '#252822', backgroundColor: '#FFFDFC', fontSize: 16 },
  searchButton: { width: 52, height: 52, borderRadius: 16, alignItems: 'center', justifyContent: 'center', backgroundColor: '#2F3A34' },
  searchButtonText: { color: '#FFF8EA', fontSize: 24 },
  askCard: { marginHorizontal: 20, marginBottom: 20, paddingVertical: 18, borderRadius: 22, backgroundColor: '#E7DDCE' },
  askInput: { minHeight: 118, marginHorizontal: 18, marginBottom: 16, color: '#252822', fontSize: 19, lineHeight: 27, textAlignVertical: 'top', fontFamily: serif },
  answerCard: { marginHorizontal: 20, marginBottom: 20, padding: 22, borderRadius: 22, backgroundColor: '#2F3A34' },
  answerEyebrow: { color: '#D7BE96', fontSize: 10, letterSpacing: 1.8, fontWeight: '700' },
  answerText: { marginTop: 10, color: '#FFF9ED', fontSize: 19, lineHeight: 28, fontFamily: serif },
  connectionCard: { marginHorizontal: 20, paddingTop: 20, paddingBottom: 22, borderRadius: 22, backgroundColor: '#E7DDCE' },
  errorText: { marginHorizontal: 20, marginBottom: 14, color: '#A8463B', fontSize: 13, lineHeight: 18 },
  noteCard: { marginHorizontal: 20, marginTop: 18, padding: 20, borderRadius: 18, backgroundColor: '#EEE7DD' },
  noteCardTitle: { marginBottom: 8, color: '#343731', fontSize: 16, fontWeight: '700' },
  noteCardText: { color: '#6C655D', fontSize: 14, lineHeight: 21 },
  tabBar: { flexDirection: 'row', paddingTop: 9, paddingBottom: Platform.OS === 'ios' ? 24 : 12, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: '#D8CFC2', backgroundColor: '#FBF8F2' },
  tab: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  tabGlyph: { color: '#978C7E', fontSize: 19, lineHeight: 22 },
  tabGlyphActive: { color: '#35443B' },
  tabLabel: { marginTop: 2, color: '#978C7E', fontSize: 10, fontWeight: '600' },
  tabLabelActive: { color: '#35443B', fontWeight: '800' },
});
